name: CI
on:
  push:
    branches:
      - develop

jobs:
  devops:
    name: Test - Unit & Integration & SonarCloud Scan & Slack WebHook
    runs-on: ubuntu-22.04 # macos-latest macos-11 windows-2019 ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Build & Unit & IT & FT
        run: mvn -B clean verify
